baseurl = "https://www2.alanchatfield.net/"
languageCode = "en-gb"
title = "Alan Chatfield"
description = "Views from the intersection of digital marketing and enterprise technology"
preserveTaxonomyNames = true
disableKinds = ["taxonomyTerm"]
assetDir = "assets"
[permalinks]
  post = "/:title/"
  tags = "/tag/:slug/"
[params]
  mainSections = ["marketing", "technology","martech","opinion"]
 [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
