---
title: "About the Author"
description: "Welcome to my blog about marketing technology and its impact on B2B marketing."
image: "https://source.unsplash.com/IpLa37Uj2Dw/1920x1080"
---

           <p class="author" style="display: block; padding-bottom: 1.5em">
                <a rel="author" href="/about" title="Alan Chatfield"><img src="//www.gravatar.com/avatar/60fa755d6b89ee9f9d59d0f957711f40?s=250&amp;d=mm&amp;r=x"></a>
                <strong><a rel="author" href="about" title="Alan Chatfield">Alan Chatfield</a></strong><br>
                <span class="muted">Senior Digital Marketing Strategist at <a href="//www.crmtechnologies.com">CRMT</a> and Marketo Certified Solutions Architect. Advisor on marketing effectiveness and marketing technology optimisation.</span>
            </p>
<p>Welcome to my blog about marketing technology and its impact on B2B marketing. These pages record some of the observations and insights I have gained as a consultant advising businesses on campaign strategy and technical architecture.</p>
<p>I am a digital marketing strategist and Marketo Certified Solutions Architect with a background in marketing automation and information technology. By day, I work for CRMT, a marketing operations agency in the UK. I advise enterprises on how to maximise their investment in marketing technology. This can involve anything from defining the funnel and architecting the marketing technology stack through to end user training and executing campaigns.</p>
<p>I got into marketing through technology. My first job was as a junior database administrator cleaning data and managing CRM databases. I was IT Manager at CRMT for many years alongside my work building campaigns in Eloqua and Marketo. Over the years, I've created enough campaigns and worked alongside enough marketers to become knowledgable in demand generation and other marketing topics.</p>
<p>My technical background can still sometimes show through, but that's no longer a bad thing. Marketing has become increasingly technical. The explosion in marketing technologies has required marketers to learn how technology can be used to enhance their campaigns. The best marketing teams are building complex technology stacks to deliver outstanding results to the business. I advise marketers on how to build the right martech stack to fit their business strategy as well as how to make the most of it once in place.</p>
<p>Technology is only useful if it solves a genuine business need. The strategy must always come first, yet many executives fail to realise this. I have seen too many marketing automation and martech implementations fail because the buyer has no real idea of what their brand new system should be used for. This can result in marketers changing their plans to fit the technology they have available, regardless of whether it is the right strategy for their business. My job is to help marketers avoid that trap.</p>
<h3 id="aboutthisblog">About this Blog</h3>
<p>This is a personal blog written in my spare time, so the content is based on whatever catches my interest. I started this site as an outlet to express my personal views on B2B marketing, marketing technology and enterprise technology, but you will also see off-topic posts about other areas clearly marked with the News &amp; Current Affairs tag. I have a politics &amp; philosophy degree so some of my News &amp; Current Affairs posts are political in nature, covering international relations and the domestic politics of other nations. I do not pretend to be an expert in everything I cover, so do let me know if anything I say is incorrect by leaving a comment on the relevant article. I unreservedly apologise for any offence caused by anything I write on these pages.</p>
<p>I'm not writing this to earn money for myself or win business for CRMT. Some of what I write will align with the views of my employer, but other opinions expressed will not. As such, everything on these pages are solely the opinion of the author and do not reflect those of CRMT or any other individual or organisation. I have included a link to CRMT on these pages, purely because the content of this site is relevant to their core business and I happen to work for them.</p>
<p>I will be writing articles for their blog too, some of which may also appear here either before or after publication on crmtechnologies.com. That is their price for allowing me to have this blog.</p>
<h3 id="gettingintouch">Getting in Touch</h3>
<p>If you want further advice or support with the marketing topics expressed in these pages do not hesitate to get in touch with CRMT. They can be contacted at <a href="https://www.crmtechnologies.com">www.crmtechnologies.com</a> or by calling +44 (0) 118 945 0030 or +1 415 659 1845.</p>
<p>If you want to get in touch with me directly, message me on <a href="https://twitter.com/alan_chatfield">Twitter</a> or email <a href="mailto:contact@alanchatfield.net">contact@alanchatfield.net</span></a>. Please do not contact me with offers of work or requests for consultancy. All paid and unpaid work should be arranged through CRMT.</p>
